### PR TITLE
Add conftest.py in order to fix pytest loading issues.

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by marxin** [comment]
The selected approach also fixes Pytest discovery in VS Code.

**Comment by Conan-Kudo** [comment]
The file needs to be added to `MANIFEST.in`

**Comment by marxin** [comment]
> The file needs to be added to `MANIFEST.in`

Thanks, done.

**Review by Conan-Kudo — APPROVED** [review]
Provided the tests pass, this looks good.

**Pull request merged**
