### PR TITLE
Make library-not-linked-against-libc a warning (#361).

### PR DESCRIPTION
**Pull request by marxin**
Add ruby-libs package that presents 2 interesting issues.

### CODE REVIEW

**Comment by scarabeusiv** [comment]
Seems the readelf crashed on Leap 15, could you check it up? Otherwise LGTM.

**Comment by marxin** [comment]
> Seems the readelf crashed on Leap 15, could you check it up? Otherwise LGTM.

So the root cause of the issue is something like:
```
readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw12/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.d_08jute/usr/lib64/ruby/stringio.so': No such file
```

Which can be a not enough space for the RPM extraction.

**Comment by marxin** [comment]
The RPM contains about 13 MB of files.

**Comment by scarabeusiv** [comment]
2 items to do here

1. stop this from happening
2. print out meaningful message so we in future won't need to dig it out

**Comment by marxin** [comment]
> 2\. print out meaningful message so we in future won't need to dig it out

I've just done this. Please take a look at the Leap issue.

**Comment by scarabeusiv** [comment]
```
ruby-libs.x86_64: E: readelf-failed /usr/lib64/libruby.so.2.7.0 readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/libruby.so.2.7.0': No such file

readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/libruby.so.2.7.0': No such file

readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/libruby.so.2.7.0': No such file

readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/libruby.so.2.7.0': No such file

readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/libruby.so.2.7.0': No such file

ruby-libs.x86_64: E: readelf-failed /usr/lib64/ruby/cgi/escape.so readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/ruby/cgi/escape.so': No such file

readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/ruby/cgi/escape.so': No such file

readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/ruby/cgi/escape.so': No such file

readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/ruby/cgi/escape.so': No such file

readelf: Error: '/tmp/pytest-of-root/pytest-0/popen-gw0/test_fedora_ruby_package_binar0/rpmlint.ruby-libs-2.7.0-1.fc32.x86_64.rpm.c9jwde_v/usr/lib64/ruby/cgi/escape.so': No such file

```

I wonder why the extractor is not working, as it invokes the pkg.py subshell to unpack it will be pain to figure :((

**Comment by marxin** [comment]
> I wonder why the extractor is not working, as it invokes the pkg.py subshell to unpack it will be pain to figure :((

Can you somehow hack it (log stderr somewhere) and locally test in `pod2man` with Leap?

**Comment by scarabeusiv** [comment]
cpio complains about it a lot: [error.log](https://github.com/rpm-software-management/rpmlint/files/4122467/error.log)

If the cpio can't read the data I am willing to bet it is because of the compression our rpm can't comprehend.

**Comment by Conan-Kudo** [comment]
SUSE Leap can't read zstd-compressed RPMs yet. 😩

**Comment by marxin** [comment]
> If the cpio can't read the data I am willing to bet it is because of the compression our rpm can't comprehend.

I've tried older Fedora 30 package and the issue does not appear there.
So that I would wait a bit as `zstd` will be supported in Leap in a short time.

**Comment by juhp** [comment]
See also related Fedora bugs for ghc:

https://bugzilla.redhat.com/show_bug.cgi?id=1749738
https://bugzilla.redhat.com/show_bug.cgi?id=1719810

**Comment by scarabeusiv** [comment]
As we borked rawhide and we are processing the maint-update for Leap to actually read the zstd format (and other checks actually do pass) I will merge this in...

**Pull request merged**
