### PR TITLE
PythonCheck: Support complex python requirements

### PR DESCRIPTION
**Pull request by danigm**
Improves the requirements regular expression to support complex rpm requirements definitions like:
  (python310-jupyter-server >= 1.15 with python310-jupyter-server < 3)

Fix https://github.com/rpm-software-management/rpmlint/issues/1057

### CODE REVIEW

**Comment by bnavigator** [comment]
Here's another false positive warning, because the python classifiers are not understood. The warnings even contradict each other:

```
[   25s] python310-scikit-build.noarch: W: python-missing-require tomli;
[   25s] python310-scikit-build.noarch: W: python-missing-require typing-extensions
[   25s] python311-scikit-build.noarch: W: python-missing-require tomli;
[   25s] python311-scikit-build.noarch: W: python-missing-require typing-extensions
[   25s] python39-scikit-build.noarch: W: python-missing-require tomli;
[   25s] python39-scikit-build.noarch: W: python-missing-require typing-extensions
[   25s] The python package declare some requirement that's not detected in the rpm
[   25s] package. Please, verify that all dependencies are added as Requires.
[   25s] 
[   25s] python310-scikit-build.noarch: W: python-leftover-require python310-tomli
[   25s] python39-scikit-build.noarch: W: python-leftover-require python39-tomli
[   25s] Some python module Requires can't be found in the python package requirements
[   25s] declaration. Please verify that all dependencies are really needed.
```

```specfile
%if %{python_version_nodots} < 38
Requires:       python-typing-extensions >= 3.7
%endif
%if %{python_version_nodots} < 311
Requires:       python-tomli
%endif
```

```toml
dependencies = [
    'distro',
    'packaging',
    'setuptools>=42.0.0',
    'tomli; python_version<"3.11"',
    'typing-extensions>=3.7; python_version<"3.8"',
    'wheel>=0.32.0',
]
```

**Review by marxin — CHANGES_REQUESTED** [review]
Can you please attach a test-case so we won't regress in the future?

**Comment by s-t-e-v-e-n-k** [comment]
Extras are not understood either:

```
[   27s] python310-weasyprint.noarch: W: python-missing-require fonttools[woff]
[   27s] python311-weasyprint.noarch: W: python-missing-require fonttools[woff]
[   27s] python39-weasyprint.noarch: W: python-missing-require fonttools[woff]
```

Which also leads to other warnings due to that:

```
[   27s] python310-weasyprint.noarch: W: python-leftover-require python310-Brotli
[   27s] python310-weasyprint.noarch: W: python-leftover-require python310-FontTools
[   27s] python310-weasyprint.noarch: W: python-leftover-require python310-zopfli
```

**Comment by bnavigator** [comment]
While you're at it:

python-hatch.spec:

```spec
%{?python_enable_dependency_generator}
```

```
[   18s] python310-hatch.noarch: W: python-missing-require click
[   18s] python310-hatch.noarch: W: python-missing-require hatchling
[   18s] python310-hatch.noarch: W: python-missing-require httpx
[   18s] python310-hatch.noarch: W: python-missing-require hyperlink
[   18s] python310-hatch.noarch: W: python-missing-require keyring
[   18s] python310-hatch.noarch: W: python-missing-require packaging
[   18s] python310-hatch.noarch: W: python-missing-require pexpect
[   18s] python310-hatch.noarch: W: python-missing-require platformdirs
[   18s] python310-hatch.noarch: W: python-missing-require pyperclip
[   18s] python310-hatch.noarch: W: python-missing-require rich
[   18s] python310-hatch.noarch: W: python-missing-require shellingham
[   18s] python310-hatch.noarch: W: python-missing-require tomli-w
[   18s] python310-hatch.noarch: W: python-missing-require tomlkit
[   18s] python310-hatch.noarch: W: python-missing-require userpath
[   18s] python310-hatch.noarch: W: python-missing-require virtualenv
[   18s] python311-hatch.noarch: W: python-missing-require click
[   18s] python311-hatch.noarch: W: python-missing-require hatchling
[   18s] python311-hatch.noarch: W: python-missing-require httpx
[   18s] python311-hatch.noarch: W: python-missing-require hyperlink
[   18s] python311-hatch.noarch: W: python-missing-require keyring
[   18s] python311-hatch.noarch: W: python-missing-require packaging
[   18s] python311-hatch.noarch: W: python-missing-require pexpect
[   18s] python311-hatch.noarch: W: python-missing-require platformdirs
[   18s] python311-hatch.noarch: W: python-missing-require pyperclip
[   18s] python311-hatch.noarch: W: python-missing-require rich
[   18s] python311-hatch.noarch: W: python-missing-require shellingham
[   18s] python311-hatch.noarch: W: python-missing-require tomli-w
[   18s] python311-hatch.noarch: W: python-missing-require tomlkit
[   18s] python311-hatch.noarch: W: python-missing-require userpath
[   18s] python311-hatch.noarch: W: python-missing-require virtualenv
[   18s] python39-hatch.noarch: W: python-missing-require click
[   18s] python39-hatch.noarch: W: python-missing-require hatchling
[   18s] python39-hatch.noarch: W: python-missing-require httpx
[   18s] python39-hatch.noarch: W: python-missing-require hyperlink
[   18s] python39-hatch.noarch: W: python-missing-require keyring
[   18s] python39-hatch.noarch: W: python-missing-require packaging
[   18s] python39-hatch.noarch: W: python-missing-require pexpect
[   18s] python39-hatch.noarch: W: python-missing-require platformdirs
[   18s] python39-hatch.noarch: W: python-missing-require pyperclip
[   18s] python39-hatch.noarch: W: python-missing-require rich
[   18s] python39-hatch.noarch: W: python-missing-require shellingham
[   18s] python39-hatch.noarch: W: python-missing-require tomli-w
[   18s] python39-hatch.noarch: W: python-missing-require tomlkit
[   18s] python39-hatch.noarch: W: python-missing-require userpath
[   18s] python39-hatch.noarch: W: python-missing-require virtualenv
[   18s] The python package declare some requirement that's not detected in the rpm
[   18s] package. Please, verify that all dependencies are added as Requires.
```

```
$ rpm -q --requires /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/home/abuild/rpmbuild/RPMS/noarch/python311-hatch-1.7.0-0.noarch.rpm
(python3.11dist(pexpect) >= 4.8 with python3.11dist(pexpect) < 5)
(python3.11dist(userpath) >= 1.7 with python3.11dist(userpath) < 2)
/bin/sh
/bin/sh
/usr/bin/python3.11
git-core
python(abi) = 3.11
python3.11dist(click) >= 8.0.3
python3.11dist(hatchling) >= 1.14
python3.11dist(httpx) >= 0.22
python3.11dist(hyperlink) >= 21
python3.11dist(keyring) >= 23.5
python3.11dist(packaging) >= 21.3
python3.11dist(platformdirs) >= 2.5
python3.11dist(pyperclip) >= 1.8.2
python3.11dist(rich) >= 11.2
python3.11dist(shellingham) >= 1.4
python3.11dist(tomli-w) >= 1
python3.11dist(tomlkit) >= 0.11.1
python3.11dist(virtualenv) >= 20.16.2
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
rpmlib(RichDependencies) <= 4.12.0-1
update-alternative
```

**Review by dirkmueller — APPROVED** [review]

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
