### PR TITLE
Tmpfiles %ghost

### PR DESCRIPTION
**Pull request by kstreitova**
We want rpmlint to check if a tmpfile is listed as a %ghost in the %files. In fact, it can't be there without %ghost directive (rpm build would fail) so it's enough to check if it's in the filelist. I added this fact to the docstring so it should be more clear now.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
> In fact, it can't be there without %ghost directive (rpm build would fail)

Why do you think this is true?

**Comment by kstreitova** [comment]
Because the tmpfile file doesn't exist in the time of the build. Therefore (without %ghost) it fails in the "Processing files" section with "File not found" RPM build error.

**Comment by Conan-Kudo** [comment]
That assumes someone actually puts the file in the file list. Most of the time, they don't. Unless you have a brp that evaluates the tmpfiles and forces them to exist, which would be bad for the reasons you stated earlier.

**Comment by scarabeusiv** [comment]
Yes and we agreed in that referenced ticket that the files created by systemd should be marked as %ghost to get them pruned on pkg uninstall, so what is the issue, this implements exactly what was the decision in #326 ...

**Comment by Conan-Kudo** [comment]
I'm just confused how this would be enforced.

**Comment by kstreitova** [comment]
@Conan-Kudo can you be more specific about what concerns you in this PR exactly, please?

**Comment by Conan-Kudo** [comment]
@kstreitova Is this reading the tmpfiles listing and checking if they're also in the rpm files list?

**Pull request merged**
