### PR TITLE
WIP: Use local variables where isn't needed instance variable.

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by scarabeusiv** [comment]
Can't we use that 'binaryornot' package even maybe?

**Comment by mimi1vx** [comment]
> Can't we use that 'binaryornot' package even maybe for the [191d279](https://github.com/rpm-software-management/rpmlint/commit/191d279688e354f9bb7e04bc459ef544e7586b4c)?

not, this package is totally different:D I think originally was +- copy/paste from this package. But now `binaryornot` simply guess the type of file from the ratio of non-ASCII characters in first 1024 bytes.

**Comment by scarabeusiv** [comment]
Okay then just kill the darn comment ;)

**Comment by marxin** [comment]
I like the suggested changes.

**Comment by marxin** [comment]
@mimi1vx: can you please rebase it?

**Comment by Conan-Kudo** [comment]
@scarabeusiv @mimi1vx Why was this merged? It's marked as WIP...

**Comment by scarabeusiv** [comment]
@Conan-Kudo Ondrej wanted to work on it more, but didn't manage; it was acceptable as it is now and even gave bit speed boost to binarycheck :)

**Pull request merged**
