### PR TITLE
Remove man, perl and elfutils from Docker files.

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by scarabeusiv** [comment]
I wonder if we need groff too.

**Comment by scarabeusiv** [comment]
Also how the ... your change broke spelling on leap :D

**Comment by marxin** [comment]
> Also how the ... your change broke spelling on leap :D

That's strange. The `man` package removal is responsible for that. Debugging right now..

**Comment by marxin** [comment]
> I wonder if we need groff too.

It's needed here:
https://github.com/rpm-software-management/rpmlint/blob/1473fab69dce38bf1c76415ec49c9d430263c54f/rpmlint/checks/FilesCheck.py#L847-L853

**Comment by marxin** [comment]
> That's strange. The `man` package removal is responsible for that. Debugging right now..

So `man` installed `glibc-locale`. Adding the package fixes the problem.

**Comment by scarabeusiv** [comment]
@marxin that files check honestly sounds useless so it might be even killed (or open it as separate ticket plz).

**Comment by marxin** [comment]
> @marxin that files check honestly sounds useless so it might be even killed (or open it as separate ticket plz).

Sure, doing that in #472.

**Pull request merged**
