### PR TITLE
Drop online checks

### PR DESCRIPTION
**Pull request by scarabeusiv**

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@scarabeusiv Why are we killing the optional network-based checks?

**Comment by Conan-Kudo** [comment]
@scarabeusiv While SUSE distributions can't use these checks because of OBS, I'm pretty sure everyone else actually relies on them as part of the lint checking.

**Comment by scarabeusiv** [comment]
nobody else uses the rpmlint coherently enough and the current implementation is quite sucky.

the https is handled by the spec-cleaner and the speccheck test if anything should be something like sourcestest and actually done properly like source validation service in obs.

**Comment by Conan-Kudo** [comment]
@scarabeusiv No other distribution using rpmlint uses OBS. Checks in ROSA and OMV's ABF instances, for example, rely on rpmlint. Fedora's `fedora-review` uses rpmlint as part of the review process and leverages these checks. ALT Linux and PLD Linux also use rpmlint in similar manners.

OBS usage of rpmlint only works using a perverted build of rpmlint with a weird configuration and install path anyway.

**Comment by scarabeusiv** [comment]
Again the https check is better offloaded to spec-cleaner because why warn about something when you can automatically fix it.
The two checks that are extra in speccheck are not entirely correct and should be done differently. I can re-create them properly if they are really used by some review process...

**Comment by Conan-Kudo** [comment]
@scarabeusiv If spec-cleaner wasn't so fully SUSE-specific, I'd consider that argument.

But yes, they are used by some people for their review processes. The Mandriva family (where rpmlint comes from!) relies on it pretty heavily.

**Comment by scarabeusiv** [comment]
I have no problem in merging support of other distros in spec-cleaner. Nobody ever bothered creating PRs. And it ain't like I didn't promote it.

**Comment by Conan-Kudo** [comment]
> I have no problem in merging support of other distros in spec-cleaner. Nobody ever bothered creating PRs. And it ain't like I didn't promote it.

Well, actually I never heard of spec-cleaner until I got involved in openSUSE a few years ago... :(

**Comment by scarabeusiv** [comment]
Ouky for the online md5 checks I will create new object that will really properly validate the stuff (not using md5 :P) and it will automatically detects if it can go online and do the check if it can..

**Comment by Conan-Kudo** [comment]
@scarabeusiv I would greatly appreciate it. Thanks!

**Comment by scarabeusiv** [comment]
In we go with the #254 putting it back later.

**Pull request merged**
