### PR TITLE
Small tweaks to the container setup for CI

### PR DESCRIPTION
**Pull request by Conan-Kudo**

### CODE REVIEW

**Comment by scarabeusiv** [comment]
Interesting fedoradev flake reports more stuff than tumbleweed one, yet they are on the same version...

**Comment by Conan-Kudo** [comment]
@scarabeusiv I think the difference is that Fedora Rawhide is already on Python 3.7, which means we have a new Deprecation to deal with.

**Comment by scarabeusiv** [comment]
Hmm looking at the fail it seems bogus actually :(

**Comment by scarabeusiv** [comment]
Well since the same thing is exposed on latest TW lets merge this and figure it out.

**Pull request merged**
