### PR TITLE
Various CI updates

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This includes various CI updates, see each commit for individual explanations.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Leap 15.3 mirrors seem to be kind of broken at the moment, [filed a ticket about it](https://progress.opensuse.org/issues/92716).

**Comment by TomasTomecek** [comment]
Please let us know if you run into issues with the branch builds. I wonder if you want those builds to happen in your namespace rather than in ours.

**Comment by Conan-Kudo** [comment]
@TomasTomecek Doesn't doing it in another namespace require storing credentials somewhere?

**Comment by TomasTomecek** [comment]
> @TomasTomecek Doesn't doing it in another namespace require storing credentials somewhere?

luckily not, you just need to grant packit the permission to build in your namespace: the workflow is that packit requests those permissions and you just need to approve the permission in the COPR web ui

**Comment by Conan-Kudo** [comment]
@TomasTomecek For now, let's leave it as-is, but I might change this in the future once I discuss this with rpmlint maintainers in Fedora.

**Pull request merged**
