### PR TITLE
descriptions: add descriptions for new FileDigest and FileMetadata ba…

### PR DESCRIPTION
**Pull request by mgerstner**
…sed checks

### CODE REVIEW

**Comment by marxin** [comment]
Please fix the failing test: `test/test_file_digest.py:57: AssertionError`.

**Comment by mgerstner** [comment]
the test should be working again now

**Comment by marxin** [comment]
Please rebase the patchset on top of the current `opensuse` branch.

**Comment by marxin** [comment]
I'm sorry, but I've made one more rebase in the meantime..

**Comment by marxin** [comment]
Thanks.

**Pull request merged**
