### PR TITLE
Enable again Fedora dev in Travis.

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by scarabeusiv** [comment]
This is waiting on fedoradev to fix their 32bit loading.

**Comment by marxin** [comment]
I guess the problematic test should be skipped now as we check for 32-bit `glibc` support.

**Comment by scarabeusiv** [comment]
still fails.

**Comment by marxin** [comment]
Then Fedoradev is somehow broken :/

**Comment by marxin** [comment]
It's even worse now:
```
E       assert 'no-ldconfig-symlink /lib64/libutil-2.29.so' in "fake: E: ldd-failed /lib64/libutil-2.29.so /usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF...`/usr/src/rpmlint/test/readelf/libutil-2.29.so'\n\nExecuting ldd on this file failed, all checks could not be run.\n\n"
test/test_readelf_parser.py:209: AssertionError
_______________________________ test_call_mktemp _______________________________
[gw0] linux -- Python 3.9.0 /usr/bin/python3
binariescheck = (<rpmlint.filter.Filter object at 0x7f91aefbdd00>, <rpmlint.checks.BinariesCheck.BinariesCheck object at 0x7f91aefbddf0>)
    @pytest.mark.skipif(not IS_X86_64, reason='x86-64 only')
    def test_call_mktemp(binariescheck):
        output, test = binariescheck
    
        run_elf_checks(test, FakePkg('fake'), get_full_path('call-mktemp'), '/bin/call-mktemp')
        out = output.print_results(output.results)
>       assert 'E: call-to-mktemp /bin/call-mktemp' in out
E       assert 'E: call-to-mktemp /bin/call-mktemp' in "fake: E: ldd-failed /bin/call-mktemp /usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\nl...for `/usr/src/rpmlint/test/readelf/call-mktemp'\n\nExecuting ldd on this file failed, all checks could not be run.\n\n"
test/test_readelf_parser.py:219: AssertionError
_____________________________ test_call_setgroups ______________________________
[gw0] linux -- Python 3.9.0 /usr/bin/python3
binariescheck = (<rpmlint.filter.Filter object at 0x7f91aec4ea00>, <rpmlint.checks.BinariesCheck.BinariesCheck object at 0x7f91aec4e910>)
    @pytest.mark.skipif(not IS_X86_64, reason='x86-64 only')
    def test_call_setgroups(binariescheck):
        output, test = binariescheck
    
        run_elf_checks(test, FakePkg('fake'), get_full_path('call-setgroups'), '/bin/call-setgroups')
        out = output.print_results(output.results)
>       assert 'E: missing-call-to-setgroups-before-setuid /bin/call-setgroups' in out
E       assert 'E: missing-call-to-setgroups-before-setuid /bin/call-setgroups' in "fake: E: ldd-failed /bin/call-setgroups /usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)... `/usr/src/rpmlint/test/readelf/call-setgroups'\n\nExecuting ldd on this file failed, all checks could not be run.\n\n"
test/test_readelf_parser.py:228: AssertionError
___________________________ test_call_gethostbyname ____________________________
[gw0] linux -- Python 3.9.0 /usr/bin/python3
binariescheck = (<rpmlint.filter.Filter object at 0x7f91aee6f970>, <rpmlint.checks.BinariesCheck.BinariesCheck object at 0x7f91aee6feb0>)
    @pytest.mark.skipif(not IS_X86_64, reason='x86-64 only')
    def test_call_gethostbyname(binariescheck):
        output, test = binariescheck
    
        run_elf_checks(test, FakePkg('fake'), get_full_path('hostname'), '/usr/bin/hostname')
        out = output.print_results(output.results)
>       assert 'W: binary-or-shlib-calls-gethostbyname' in out
E       assert 'W: binary-or-shlib-calls-gethostbyname' in "fake: E: ldd-failed /usr/bin/hostname /usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\n...on for `/usr/src/rpmlint/test/readelf/hostname'\n\nExecuting ldd on this file failed, all checks could not be run.\n\n"
```

**Pull request closed without merging**
