### PR TITLE
Files in /etc/pam.d/ should be moved to /usr

### PR DESCRIPTION
**Pull request by schubi2**
https://github.com/schubi2/rpmlint/pull/new/opensuse-etc

### CODE REVIEW

**Comment by schubi2** [comment]
I have already fixed all packages in factory which I have found on the latest TW build.

**Comment by marxin** [comment]
@mgerstner @thesp0nge @FilippoBonazziSUSE Can you please approve this change?

**Comment by mgerstner** [comment]
Is this coordinated with the PAM maintainers? Currently we still have about 40 packages in Factory that ship files in there. Among them is pam-config, but there it probably needs to stay that way, because the files are generated at runtime.

**Comment by schubi2** [comment]
> Is this coordinated with the PAM maintainers? Currently we still have about 40 packages in Factory that ship files in there. Among them is pam-config, but there it probably needs to stay that way, because the files are generated at runtime.
Yes, I have gotten this task by Thorsten Kukuk one of the pam maintainers to do this. I have taken a factory TW snapshot from the mid of December and have already fixed all packages which are on the DVD at least. So, there should not left very much packages anymore.
If you see any package which is still not be changed. Please tell me. I am used to fix it :-)

**Comment by Conan-Kudo** [comment]
In Fedora, this is set to `/usr/share/pam.d`. Is openSUSE putting them in the same path?

**Comment by Conan-Kudo** [comment]
Cf. https://src.fedoraproject.org/rpms/pam/c/e739be9b4cd353037cbdf2b17ee9fad9e4e76623?branch=rawhide

**Comment by mgerstner** [comment]
> Yes, I have gotten this task by Thorsten Kukuk one of the pam maintainers to do this. I have taken a factory TW snapshot from the mid of December and have already fixed all packages which are on the DVD at least. So, there should not left very much packages anymore. If you see any package which is still not be changed. Please tell me. I am used to fix it :-)

Currently these packages still use the old path:

```
krb5-client-1.20.1-2.1.x86_64.rpm            /etc/pam.d/ksu
pam-config-1.8-1.1.x86_64.rpm                /etc/pam.d/common-account-pc
pam-config-1.8-1.1.x86_64.rpm                /etc/pam.d/common-auth-pc
pam-config-1.8-1.1.x86_64.rpm                /etc/pam.d/common-password-pc
pam-config-1.8-1.1.x86_64.rpm                /etc/pam.d/common-session-pc
postfix-3.7.3-2.1.x86_64.rpm                 /etc/pam.d/smtp
budgie-screensaver-5.1.0+0-2.1.x86_64.rpm    /etc/pam.d/budgie-screensaver
cinnamon-screensaver-5.6.2-1.1.x86_64.rpm    /etc/pam.d/cinnamon-screensaver
courier-imap-5.2.1-1.1.x86_64.rpm            /etc/pam.d/imap
courier-imap-5.2.1-1.1.x86_64.rpm            /etc/pam.d/pop3
deepin-daemon-5.14.45-1.1.x86_64.rpm         /etc/pam.d/deepin-auth-keyboard
enlightenment-0.25.4-1.1.x86_64.rpm          /etc/pam.d/enlightenment
freeradius-server-3.0.25-5.1.x86_64.rpm      /etc/pam.d/radiusd
frr-8.4-1.1.x86_64.rpm                       /etc/pam.d/frr
cockpit-ws-276.1-1.3.x86_64.rpm              /etc/pam.d/cockpit
sddm-0.19.0-8.1.x86_64.rpm                   /etc/pam.d/sddm
sddm-0.19.0-8.1.x86_64.rpm                   /etc/pam.d/sddm-autologin
sddm-0.19.0-8.1.x86_64.rpm                   /etc/pam.d/sddm-greeter
ppp-2.4.9-2.2.x86_64.rpm                     /etc/pam.d/ppp
sendmail-8.17.1-5.2.x86_64.rpm               /etc/pam.d/smtp
vsftpd-3.0.5-8.1.x86_64.rpm                  /etc/pam.d/vsftpd
xfce4-screensaver-4.16.0-2.12.x86_64.rpm     /etc/pam.d/xfce4-screensaver
mate-screensaver-1.26.1-1.6.x86_64.rpm       /etc/pam.d/mate-screensaver
mrsh-server-2.12-12.11.x86_64.rpm            /etc/pam.d/mrlogin
mrsh-server-2.12-12.11.x86_64.rpm            /etc/pam.d/mrsh
openwsman-server-2.7.2-1.1.x86_64.rpm        /etc/pam.d/openwsman
pam_pkcs11-0.6.12-3.3.x86_64.rpm             /etc/pam.d/common-auth-smartcard
pleaser-0.5.1~git0.ce9627c-6.3.x86_64.rpm    /etc/pam.d/please
pleaser-0.5.1~git0.ce9627c-6.3.x86_64.rpm    /etc/pam.d/pleaseedit
postfix-bdb-3.7.3-2.1.x86_64.rpm             /etc/pam.d/smtp
proftpd-1.3.7e-2.2.x86_64.rpm                /etc/pam.d/proftpd
pure-ftpd-1.0.51-1.2.x86_64.rpm              /etc/pam.d/pure-ftpd
rstudio-server-2022.02.2+485-1.5.x86_64.rpm  /etc/pam.d/rstudio
sblim-sfcb-1.4.9-14.6.x86_64.rpm             /etc/pam.d/sfcb
swaylock-1.7-1.1.x86_64.rpm                  /etc/pam.d/swaylock
uucp-1.07-3.10.x86_64.rpm                    /etc/pam.d/uucp
xpra-5.0+git20221127.3e61ef1c-1.1.x86_64.rpm /etc/pam.d/xpra
xrdp-0.9.20-3.1.x86_64.rpm                   /etc/pam.d/xrdp-sesman
```

**Comment by mgerstner** [comment]
Although this is not really security related (and thus I'm not really entitled to judge) I don't see any problem with this change, if it is coordinated with the PAM maintainers.

**Comment by marxin** [comment]
Am I correct that the submit request with this change will take some time as it's going to influence quite some packages?

**Comment by marxin** [comment]
> Am I correct that the submit request with this change will take some time as it's going to influence quite some packages?

No, as it has badness equal to 1.

**Comment by mgerstner** [comment]
> Am I correct that the submit request with this change will take some time as it's going to influence quite some packages?

As I see it this is just an additional diagnostic without badness attached to it. So there shouldn't be a need to wait for any package adaptions, rather it is an enabler for the package adaptions.

**Comment by schubi2** [comment]
Thanks Matthias for the list. I have changed all these packages and have added an rpmlintrc file for pam-config.

**Pull request merged**
