### PR TITLE
Add RCLinksCheck.

### PR DESCRIPTION
**Pull request by marxin**
The check is about interaction in between `systemd` and `init.d`.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Not permitting this for upstream. You should also retire this as policy in openSUSE.

**Comment by marxin** [comment]
> Not permitting this for upstream. You should also retire this as policy in openSUSE.

Yep, it was intended for `opensuse` branch.
@scarabeusiv: Do we still want to follow the policy in openSUSE?

**Comment by Conan-Kudo** [comment]
@marxin The systemd shadowed initscript probably belongs in `SysVInitOnSystemdCheck` instead of here.

**Comment by scarabeusiv** [comment]
Yeah the rclink policy is still adhered, and most of our documentation sadly points to it so I don't see that being deprecated any time soon.

**Comment by Conan-Kudo** [comment]
@scarabeusiv If rpmlint doesn't enforce it anymore, then it'll slowly go away as it's not needed.

**Comment by scarabeusiv** [comment]
It is enforced as of now on Tumbleweed so we should not regress from there. Maybe there could be some discussion on -factory if it is really needed again...

**Pull request closed without merging**
