### PR TITLE
polkit-rules-whitelist: self auth as admin (bsc#1215652)

### PR DESCRIPTION
**Pull request by wfrisch**
fix typo

### CODE REVIEW

**Comment by FilippoBonazziSUSE** [comment]
Wow, so the hashes were both wrong and off by 1 character at the end.

Also, is the package name correct or shouldn't it be fixed as well?

**Comment by wfrisch** [comment]
It should be fine now. Please double-check though.

**Review by FilippoBonazziSUSE — APPROVED** [review]
Package names are correct and hashes are identical to the ones reported by OBS

**Comment by wfrisch** [comment]
Thanks, and sorry for the trouble.
A basic linter for the toml files would be helpful.

**Comment by FilippoBonazziSUSE** [comment]
@danigm we've been seeing these mageia cauldron CI failures for a few days now. I believe they are unrelated to our changes, so I will merge this PR. Do you know what's up with them though?

**Comment by danigm** [comment]
> @danigm we've been seeing these mageia cauldron CI failures for a few days now. I believe they are unrelated to our changes, so I will merge this PR. Do you know what's up with them though?

Looks like a problem related with the rpm package and a dnf plugin that's not updated, python3-dnf-plugins-core version 4.3.1 and it's fixed since version 4.4.1

**Comment by danigm** [comment]
> Looks like a problem related with the rpm package and a dnf plugin that's not updated, python3-dnf-plugins-core version 4.3.1 and it's fixed since version 4.4.1

I've just [reported this bug](https://bugs.mageia.org/show_bug.cgi?id=32527) and disabled the [mageia in CI](https://github.com/rpm-software-management/rpmlint/commit/57e75f34f8ea369379234841e0f6e232b80bd6e3) until it's solved.

**Pull request merged**
