### PR TITLE
iio-sensor-proxy: move dbus system.d file to /usr (bsc#1204055)

### PR DESCRIPTION
**Pull request by FilippoBonazziSUSE**

### CODE REVIEW

**Comment by mgerstner** [comment]
same issue here as in the other two whitelisting adjustments

**Comment by FilippoBonazziSUSE** [comment]
I don't get it - I got the digest value from OBS in the rpmlint failure log. Is that wrong?

**Comment by FilippoBonazziSUSE** [comment]
Oh, I see. I guess that does not apply to the `shell` digest, and that's how I was able to get a match to an existing file using `sha256` in #945 .

**Comment by marxin** [comment]
`shell` digest also ignores whitespaces.

You can see if there's a diff by running something like `./tools/get_whitelisting_digest.py /etc/dbus-1/system.d/net.hadess.SensorProxy.conf --filter=xml --show-result > after && diff -u /etc/dbus-1/system.d/net.hadess.SensorProxy.conf after`

**Comment by FilippoBonazziSUSE** [comment]
I see. I just got lucky then... Will fix

**Review by mgerstner — APPROVED** [review]

**Pull request merged**
