### PR TITLE
Remove flaky macro expansion of private_so_paths (#292).

### PR DESCRIPTION
**Pull request by marxin**
The macro expansion leads to a unstable expected locations.

### CODE REVIEW

**Comment by marxin** [comment]
#292

**Comment by Conan-Kudo** [comment]
@marxin That code seems like it works as intended...?

**Comment by marxin** [comment]
> @marxin That code seems like it works as intended...?

Ok, then I make a PR to the `opensuse` branch.

**Comment by Conan-Kudo** [comment]
@marxin Well, I want to know what's wrong that led to this patch being made. I'm not necessarily saying "no" out of the gate here.

**Comment by marxin** [comment]
@scarabeusiv Can you please help us here?

**Comment by scarabeusiv** [comment]
This expansion was flaky and caused trouble for us in openSUSE because it is evaluated in some case to other stuff than what was anticipated. Now even fedora people complain that it expands to stuff with output to stdout. As such it is better to just not do it (like we do in openSUSE) and come up with better way how to achieve the result if desirable...

**Comment by Conan-Kudo** [comment]
@scarabeusiv Sounds good to me. Could you create an issue for doing this better? I'll merge this for now.

**Pull request merged**
