### PR TITLE
[opensuse] Move tss fapi config to new package

### PR DESCRIPTION
**Pull request by gmbr3**
* Avoid breaking SLPP

### CODE REVIEW

**Comment by gmbr3** [comment]
https://build.opensuse.org/request/show/1137558

**Comment by gmbr3** [comment]
> > * Avoid breaking SLPP
> 
> Can you please tell us what "SLPP" is?

Abbreviation for Shared Library Packaging Policy
https://en.opensuse.org/openSUSE:Shared_library_packaging_policy

**Comment by mgerstner** [comment]
> > > * Avoid breaking SLPP
> > 
> > 
> > Can you please tell us what "SLPP" is?
> 
> Abbreviation for Shared Library Packaging Policy https://en.opensuse.org/openSUSE:Shared_library_packaging_policy

Thanks for the explanation.

Can you please adjust the commit message to make it clear, something like:

```
systemd-tmpfiles whitelist: adjust package name for libtss-fapi

The sytemd-tmpfiles configuration has been moved into a separate sub-package. Adjust the whitelisting accordingly.
```

**Comment by mgerstner** [comment]
Thank you for contributing!

**Pull request merged**
