### PR TITLE
FilesCheck: Update Python 3.6 bytecode magic value again

### PR DESCRIPTION
**Pull request by AdamWill**
This is the value for 3.6rc1, which == 3.6.0.

### CODE REVIEW

**Comment by dirkmueller** [comment]
Do you have any pointer to the cpython source equivalent of this value?

**Comment by Conan-Kudo** [comment]
@dirkmueller See here: https://github.com/python/cpython/blob/master/Lib/importlib/_bootstrap_external.py#L230-L242

**Comment by dirkmueller** [comment]
Thanks!

**Comment by AdamWill** [comment]
@dirkmueller the comment just above the changed line actually includes the link. :)

**Pull request merged**
