### PR TITLE
Support multiple config files and overriding descriptions

### PR DESCRIPTION
**Pull request by kstreitova**
A needed preparation for porting of our old rpmlint distro configs to the new toml style.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@kstreitova I'd rather see defaults and distribution/vendor provided configurations shipped in `/usr/share/rpmlint/*.toml` and admin/user overrides in `/etc/rpmlint/*.toml` and `~/.config/rpmlint/*.toml`.

**Comment by kstreitova** [comment]
> I'm confused as to why you're changing the layout. Distribution rpmlint policy configurations should always be managed separately. In general, I like most of the updates in here, but I do not think the path changing for the default configs is warranted.

The only thing I did here regarding paths was to move configdefaults.toml from rpmlint/configdefaults.toml to rpmlint/configs/configdefaults.toml. I believe that it's reasonable to have all configs at the one place and it also helps us to easily test all configuration files (as requested in #157) with test/test_lint.py/test_run_full_specs() and test_run_full_rpm(). 

I planned to have the following structure for the distro configs that we want to storage here:

configs
├── configdefaults.toml
├── Fedora
│   ├── config.toml
├── openSUSE
│   ├── config.toml
│   ├── licenses.toml
│   └── pie.toml

> @kstreitova I'd rather see defaults and distribution/vendor provided configurations shipped in `/usr/share/rpmlint/*.toml` and admin/user overrides in `/etc/rpmlint/*.toml` and `~/.config/rpmlint/*.toml`.

This rather sounds like a job for the final packaging.

**Comment by kstreitova** [comment]
After a discussion with @scarabeusiv I reworked the support for overriding descriptions from configuration file. The previous approach updated it right after the check initialization, which was nice but it was needed to call `update_description()` method for every check that uses "dynamic" descriptions. And that was prone to be omitted for the future checks. Now the descriptions are updated in the end - right before the description string is requested to be printed.

**Comment by scarabeusiv** [comment]
LGTM.

The only thing I would still not do is the default config move. We don't expect to store any further configs in rpmlint/configs/ folder and even if we allow to ship distro specific configuration they will be simply stored in git and not shipped by rpmlint by default (eg spec file should be responsible to install the right one in /etc).

**Comment by kstreitova** [comment]
Ok, I understand that you don't want to have it under rpmlint directory. I moved configdefaults.toml back to its original location. Ready to be merged.

**Comment by scarabeusiv** [comment]
Yep now it looks like we addressed all the comments, merging in.

**Pull request merged**
