### PR TITLE
Remove no-%clean-section section check.

### LINKED ISSUE #537: rpmlint 2 complains about absence of %clean
```
[   55s] libHX.spec: W: no-%clean-section
[   55s] The spec file doesn't contain a %clean section to remove the files installed
[   55s] by the %install section.
```

The `%clean` section is optional and implicit in rpm since a long time. rpmlint should not warn about it.

### PR DESCRIPTION
**Pull request by marxin**
Fixes #537.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@marxin We probably want to flip this check to be throwing errors if `%clean` is in a spec file.

**Review by Conan-Kudo — CHANGES_REQUESTED** [review]
We probably want to flip this check to be throwing errors if `%clean` is in a spec file.

**Comment by marxin** [comment]
> We probably want to flip this check to be throwing errors if `%clean` is in a spec file.

Apparently, we have ~400 packages in `openSUSE:Factory` that contains `%clean` section.
Are you sure we really want to error on that?

**Comment by Conan-Kudo** [comment]
Yes, that section should not be present since RPM has its own `%clean` logic.

**Comment by scarabeusiv** [comment]
Yep Neal is right, spec-cleaner automatically removes the section too.

**Comment by marxin** [comment]
Nice, I've just implemented the new check.

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
