### PR TITLE
checkbashisms: support --early-fail option of the script.

### PR DESCRIPTION
**Pull request by marxin**
The script approved addition of the option. With the option,
it exits right after a first error is seen:
https://salsa.debian.org/debian/devscripts/-/merge_requests/208

It speed up e.g. tar package check from 90s to 1s.

### CODE REVIEW

**Comment by scarabeusiv** [comment]
I wonder if it is good idea to bail out right away or not, also we might just enforce newer check bashism in deps rather than have huge magic to detect it.

Do we print out also the reason why it failed? If not then stopping on first detected error on the file is good, if we list all the errors then we should probably keep doing so.

**Comment by Conan-Kudo** [comment]
> I wonder if it is good idea to bail out right away or not, also we might just enforce newer check bashism in deps rather than have huge magic to detect it.

Considering `devscripts` hasn't made a release with that feature added yet, it is premature to consider making it a requirement.

**Comment by marxin** [comment]
> I wonder if it is good idea to bail out right away or not, also we might just enforce newer check bashism in deps rather than have huge magic to detect it.

Well, without the patch, `BashismsCheck` wastes quite a huge time for various packages.
Moreover, the last `devscripts` release was made 6 months ago...

> 
> Do we print out also the reason why it failed? If not then stopping on first detected error on the file is good, if we list all the errors then we should probably keep doing so.

We do not list any errors, we just check for a return code of `checkbashisms`.

**Comment by marxin** [comment]
> Considering `devscripts` hasn't made a release with that feature added yet, it is premature to consider making it a requirement.

I see. On the other hand, it's an optional run-time detection, not a requirement.

**Comment by marxin** [comment]
Added a comment, hope @scarabeusiv can merge it now..

**Comment by scarabeusiv** [comment]
Yep it does nto require new script, just uses it if it can. lgtm.

**Comment by marxin** [comment]
Thanks, please rebase me `opensuse` branch.

**Pull request merged**
