### PR TITLE
Add test in test_speccheck, modified SpecCheck.py

### PR DESCRIPTION
**Pull request by thisisshub**
This commit contains,
1. Refactored check in SpecCheck.py

2. Source-rpms in test/source

3. Tests in test_speccheck which are named with test_check_* and
    their subsequent test_check_*_not_found/applied listed as,

 - test_check_no_spec_file
- test_check_no_spec_file_not_applied
- test_check_non_utf8_spec_file
- test_check_non_utf8_spec_file_not_applied
- test_check_invalid_spec_name
- test_check_invalid_spec_name_not_applied
- test_check_non_break_space
- test_check_non_break_space_not_applied
- test_check_rpm_buildroot_usage_under_prep
- test_check_rpm_buildroot_usage_under_build
- test_check_rpm_buildroot_usage_not_applied
- test_check_make_check_outside_check_section
- test_check_make_check_inside_check_section
- test_check_make_check_outside_not_applied
- test_check_setup_not_quiet
- test_check_setup_is_quiet
- test_check_setup_not_quiet_not_applied
- test_check_setup_not_in_prep
- test_check_setup_inside_prep
- test_check_setup_not_in_prep_not_applied
- test_check_autopatch_not_in_prep
- test_check_autopatch_in_prep
- test_check_autopatch_not_in_prep_not_applied
- test_check_autosetup_not_in_prep
- test_check_autosetup_inside_prep
- test_check_autosetup_not_in_prep_not_applied
- test_check_use_of_rpm_source_dir
- test_check_use_of_rsd_not_applied
- test_check_configure_without_libdir_spec
- test_check_cwls_not_applied
- test_check_hardcoded_library_path
- test_check_hclp_not_applied
- test_check_obsolete_tag
- test_check_obsolete_tag_not_applied
- test_check_hardcoded_path_in_buildroot_tag
- test_check_hpbt_not_applied
- test_check_buildarch_instead_of_exclusivearch_tag
- test_check_biet_not_applied
- test_check_hardcoded_packager_tag
- test_check_hardcoded_packager_tag_not_applied
- test_check_hardcoded_prefix_tag
- test_check_hardcoded_prefix_tag_not_applied
- test_check_buildprereq_use
- test_check_buildprereq_use_not_applied
- test_check_bsisr
- test_check_bsisr_not_applied
- test_check_forbidden_controlchar_found
- test_check_forbidden_controlchar_not_found
- test_check_coid
- test_check_coid_found
- test_check_coid_is_found
- test_check_coid_is_found_with_single_space
- test_check_coid_is_found_with_double_space
- test_check_unversioned_explicit_version
- test_check_unversioned_explicit_version_not_found
- test_check_uev_not_applied
- test_check_unversioned_explicit_obsoletes
- test_check_unversioned_explicit_obsoletes_not_found
- test_check_ueo_not_found
- test_check_macro_in_changelog
- test_check_macro_in_changelog_not_found
- test_check_macro_in_changelog_not_applied
- test_check_libdir_macro_in_noarch_package
- test_check_lmnp_not_applied
- test_check_deprecated_grep
- test_check_deprecated_grep_not_found
- test_check_deprecated_grep_not_applied
- test_check_macro_in_comment
- test_check_macro_in_comment_not_found
- test_check_macro_in_comment_not_applied
- test_check_no_build_root_tag
- test_check_no_build_root_tag_not_applied
- test_check_no_essential_section
- test_check_no_essential_section_not_applied
- test_check_more_than_one_changelog_section
- test_check_mtocs_not_applied
- test_check_lib_package_without_mklibname
- test_check_lpwm_not_applied
- test_check_depscript_without_disabling_depgen
- test_check_depscript_without_disabling_depgen_not_found
- test_check_dwdd_not_applied
- test_check_mixed_use_of_spaces_and_tabs
- test_check_mixed_use_of_spaces_and_tabs_not_applied
- test_check_ifarch_applied_patch
- test_check_ifarch_applied_not_enforced
- test_check_patch_not_applied
- test_check_patch_not_found
- test_check_patch_not_applied_not_enforced
- test_check_invalid_url
- test_check_invalid_url_not_applied

4. Specfile in test/spec listed as,

- %autopatch-not-in-prep.spec
- %autosetup-not-in-prep.spec
- broken-syntax-in-scriptlet-requires.spec
- buildarch-instead-of-exclusivearch-tag.spec
- buildprereq-use.spec
- comparison-operator-in-deptoken.spec
- configure-without-libdir-spec.spec
- deprecated-grep.spec
- depscript-without-disabling-depgen.spec
- forbidden-controlchar-found.spec
- hardcoded-library-path.spec
- hardcoded-packager-tag.spec
- hardcoded-path-in-buildroot-tag.spec
- hardcoded-prefix-tag.spec
- %ifarch-applied-patch.spec
- invalid-url.spec
- libdir-macro-in-noarch-package.spec
- lib-package-without-%mklibname.spec
- macro-in-changelog.spec
- macro-in-comment.spec
- make-check-outside-check-section.spec
- mixed-use-of-spaces-and-tabs.spec
- more-than-one-%changelog.spec
- no-buildroot-tag.spec
- non-break-space.spec
- non-standard-group.spec
- non-utf8-spec-file.spec
- no-%%%s-section.spec
- obsolete-tag.spec
- rpm-buildroot-usage.spec
- setup-not-in-prep.spec
- setup-not-quiet.spec
- SpecCheck2.spec
- SpecCheck3.spec
- SpecCheck4.spec
- SpecCheck.spec
- SpecCheckTemp.spec
- unversioned-explicit-obsoletes.spec
- unversioned-explicit-version.spec
- use-of-RPM-SOURCE-DIR.spec

### CODE REVIEW

**Comment by thisisshub** [comment]
Currently Travis fails with the command 
`podman run -v $(pwd):/usr/src/rpmlint/ $DIST python3 -m pytest" exited with 1.` 

I recommend to clone my branch [gsoc-rpmlint](https://github.com/thisisshub/rpmlint/tree/gsoc-rpmlint) and run the test suites personally on your workstation to make sure everything works perfectly. 

Please use the following commands to run the test suites,

`cd rpmlint`

and then

- To test everything 
`sudo podman run -v $(pwd):/usr/src/rpmlint/ opensusetw python3 -m pytest --color=yes -v -s test/`

- To test test_speccheck.py individually by 
`sudo podman run -v $(pwd):/usr/src/rpmlint/ opensusetw python3 -m pytest --color=yes -v -s test/test_speccheck.py`

**Comment by scarabeusiv** [comment]
I've fixed the travis run so you can rebase on the current master and it should be passing everywhere except of leap15.1

**Comment by thisisshub** [comment]
> I've fixed the travis run so you can rebase on the current master and it should be passing everywhere except of leap15.1
I tried rebasing as you suggested yet I get failed builds from Travis. 
There's still an error in `The command "podman run -v $(pwd):/usr/src/rpmlint/ $DIST python3 -m pytest" exited with 1.` in the builds. Could you please check what could be going wrong?

**Comment by kstreitova** [comment]
Adding `no-spec-file-0-0.src.rpm` actually helped discover a bug in `SpecCheck.py`

We hit and exception in `rpmlint/checks/SpecCheck.py:check_source()` that was then catched in `rpmlint/lint.py:validate_file()`:
```
(none): E: while reading test/source/no-spec-file-0-0.src.rpm:
[Errno 2] No such file or directory: '/tmp/rpmlint.CheckInclude-1-1.src.rpm.dr55x4m6/CheckInclude.spec'
```

The problem was that `self._spec_file` and `self._spec_name` weren't set to None in `check_source()` and if there was no specfile (which is exactly the case of `no-spec-file-0-0.src.rpm`) then the previous value was used.


**Fix**:

```python
diff --git a/rpmlint/checks/SpecCheck.py b/rpmlint/checks/SpecCheck.py
index 66a8299..c279a50 100644
--- a/rpmlint/checks/SpecCheck.py
+++ b/rpmlint/checks/SpecCheck.py
@@ -126,6 +126,9 @@ class SpecCheck(AbstractCheck):
     def check_source(self, pkg):
         """Find specfile in SRPM and run spec file related checks."""
         wrong_spec = False
+        self._spec_file = None
+        self._spec_name = None
+
         for fname, pkgfile in pkg.files.items():
             if fname.endswith('.spec'):
                 self._spec_file = pkgfile.path


```

**Comment by thisisshub** [comment]
@kstreitova
Thanks, now all the tests suites pass as they should as mentioned by @scarabeusiv  above in the comments.

**Comment by scarabeusiv** [comment]
Looks good now, as the tests seem correct I am going to merge this in. Thanks.

**Pull request merged**
