### PR TITLE
Add check for binary-or-shlib-calls-gethostbyname.

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by scarabeusiv** [comment]
I wonder how big chance the check has to convince devs to report it upstream and get it fixed :)

**Comment by marxin** [comment]
> I wonder how big chance the check has to convince devs to report it upstream and get it fixed :)

Dunno, but reporting a warning seems reasonable to me.

**Comment by scarabeusiv** [comment]
Needs rebase

**Comment by marxin** [comment]
> Needs rebase

Done.

**Pull request merged**
