### PR TITLE
Adjust sddm / pam whitelistings

### PR DESCRIPTION
**Pull request by mgerstner**

### CODE REVIEW

**Comment by marxin** [comment]
The `openSUSE` CI will be fixed after https://build.opensuse.org/request/show/1043731.

**Comment by marxin** [comment]
@mgerstner: Do you want a review from your security teammates, or may I merge it?

**Review by thesp0nge — APPROVED** [review]

**Comment by thesp0nge** [comment]
@marxin I approved the changes, however, I'm unsure about those flake errors. So, please merge if they are not mandatory

**Comment by mgerstner** [comment]
> @mgerstner: Do you want a review from your security teammates, or may I merge it?

Once at least one member of the security team approved you can happily merge it. We are often confused about some of the breaking CI checks, so I recommend we approve and you merge (or complain, if something is really broken on our end) :-)

**Comment by marxin** [comment]
> Once at least one member of the security team approved you can happily merge it. We are often confused about some of the breaking CI checks, so I recommend we approve and you merge (or complain, if something is really broken on our end) :-)

Works for me! Btw. are you fine with the current workflow where we integrate the source and the configuration in a single repository? Hope it's much better than what we have before where the OBS package contains a bunch of extra patches. And the configs lived in a separate package. How do you feel about that?

**Comment by mgerstner** [comment]
> Works for me! Btw. are you fine with the current workflow where we integrate the source and the configuration in a single repository? Hope it's much better than what we have before where the OBS package contains a bunch of extra patches. And the configs lived in a separate package. How do you feel about that?

I'm happy about the current workflow, it works much smoother than in the past. Only in parts due to the technical setup, but even more so because we have someone actively taking care of this package, namely you. Thanks for doing that!

**Comment by marxin** [comment]
> Thanks for doing that!

I'm happy it makes your everyday job easier.

**Pull request merged**
