### PR TITLE
Try to use podman instead of docker to have it work on the enterprise…

### PR DESCRIPTION
**Pull request by scarabeusiv**
…y stuff too.

If it works then it is 1:1, on local build it works, even with the rootless mapping, but I dunno if travis will actually manage to run it.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@scarabeusiv `podman` doesn't exist in Ubuntu.

**Comment by scarabeusiv** [comment]
And I am looking if it could be made to work and for that I need this open so the travis triggers it for me...

**Comment by scarabeusiv** [comment]
So it seems to be operable, the only issue is that it uncovered a bug on Tubmleweed I have to fix first.

**Comment by junaruga** [comment]
I am happy to see this PR.
If you find a issue related to podman, I recommend to set `dist: xenial` to `.travis.yml`.
I am not sure which distribution version is running without setting `dist`.

podman on `dist: bionic` by root user (`sudo`) has a bug.
See my investigation on my repository.
https://github.com/junaruga/libpod/blob/feature/add-travis-ci/.travis.yml
https://travis-ci.org/junaruga/libpod/builds/592103783

**Comment by scarabeusiv** [comment]
@Conan-Kudo see, I told ya it will work :) And I even fixed a bug in TW as a result from that :)

**Comment by Conan-Kudo** [comment]
Yeah, yeah. I'll merge it once the pipeline passes.

**Pull request merged**
