### PR TITLE
[opensuse] Rebase update-alternatives check for new rpmlint

### PR DESCRIPTION
**Pull request by scarabeusiv**
Redo the update-alternatives handling upon new rpmlint approach.

We are talking about https://github.com/openSUSE/rpmlint-checks/blob/master/CheckUpdateAlternatives.py

Still needs testcase/review of functionality prior merging.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Hmm, something is tingling here... @decathorpe, do we have any guidelines specifically about alternatives in Fedora? This might be useful as a more generic check to implement policy about how alternatives should be used...

**Comment by scarabeusiv** [comment]
We use the update-alternatives from dpkg that behave slightly differently from the Fedora version of this thing.

**Comment by Conan-Kudo** [comment]
@scarabeusiv blech, really? ☹️

**Comment by scarabeusiv** [comment]
Well looking on https://docs.fedoraproject.org/en-US/packaging-guidelines/Alternatives/ if it is spot on the requirements look the same so apart from it being different implementation the results delivered should be the same?

**Comment by Conan-Kudo** [comment]
@scarabeusiv I'd think so, yes, at least from that perspective.

**Comment by scarabeusiv** [comment]
Ok I will close this PR and create new one to point to master rather than opensuse branch and we can check it up. in my view i still need to do tests anyway :)

**Pull request closed without merging**
