### PR TITLE
Move autosetup regex into config options file

### PR DESCRIPTION
**Pull request by sergey-239**
There is a `forgemeta` macro in Fedora which provides `forgeautosetup` macro with the same functionality as `autosetup`, so we would like `autosetup` regex pattern to be customizable.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
The forge macros are unmaintained in Fedora, so unless someone is stepping up to maintain them and mainline them, I don't think we should do anything.

**Comment by sergey-239** [comment]
> 
Neal, but forgemeta is quite in use: there are 231 spec out of ~22k in FC36 have it. As well it is mentioned in packaging guidelines. How that comes out?

**Comment by Conan-Kudo** [comment]
> Neal, but forgemeta is quite in use: there are 231 spec out of ~22k in FC36 have it. As well it is mentioned in packaging guidelines. How that comes out?

It was added to the guidelines when @nim-nim wrote the macros and made the Go macros dependent on them. They haven't seen significant wider adoption beyond that. When he left Fedora, the macros basically became unmaintained because nobody else knows how to work with that code.

**Comment by marxin** [comment]
Thus, I'm closing this PR for now.

**Pull request closed without merging**
