### PR TITLE
Fix the zstd compression detection

### PR DESCRIPTION
**Pull request by scarabeusiv**
As it needs the zstd import we are passing we need the new dep
(not detected by tests as we don't have anything zstd compressed there).

Also fix other flake8 errors.

### CODE REVIEW

**Comment by scarabeusiv** [comment]
@Conan-Kudo how is zstd python module called on Fedora?

**Comment by Conan-Kudo** [comment]
@scarabeusiv Working on adding it to Fedora now: https://bugzilla.redhat.com/show_bug.cgi?id=1870571

**Comment by Conan-Kudo** [comment]
@scarabeusiv This should now be available in Fedora.

**Comment by Conan-Kudo** [comment]
@scarabeusiv This should now be available in Fedora: https://bodhi.fedoraproject.org/updates/FEDORA-2020-7597c40a16

**Comment by scarabeusiv** [comment]
In we go then :)

**Pull request merged**
