### PR TITLE
openSUSE scoring.toml: remove missing checks.

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by scarabeusiv** [comment]
Those are probably openSUSE only specific?

**Comment by scarabeusiv** [comment]
Add them to separate file and that should go to opensuse branch

**Comment by marxin** [comment]
> Those are probably openSUSE only specific?

Yes.

**Comment by marxin** [comment]
> Add them to separate file and that should go to opensuse branch

Yep, I'll do it as soon as this is merged.

**Pull request merged**
