### PR TITLE
Implement exclude option for Rpmdiff (rebase of #207).

### LINKED ISSUE #206: RFE: rpmdiff exclude paths
I am often swamped by the follwoing output of rpmdiff:

```
added       /usr/lib/.build-id/00/9e139e373a9cac5c1630f8fe9d0846af32cb8f
removed     /usr/lib/.build-id/00/aa7d62a26f8086f31e51fe01c30b7be4055bf6
removed     /usr/lib/.build-id/01/818b03c8380e11d926afa5fb5a99eb028d7679
added       /usr/lib/.build-id/01/d3a68334de5bf822a642567ecd51885d7cc061
added       /usr/lib/.build-id/03
added       /usr/lib/.build-id/03/59be0a72e625593f6d2584ec6516b6f9468cbd
added       /usr/lib/.build-id/05
added       /usr/lib/.build-id/05/13d47a66180a50b1aaebb903117ea7f87b166c
added       /usr/lib/.build-id/07
added       /usr/lib/.build-id/07/289c16783219d28092ddb6d488c9a391f93941
added       /usr/lib/.build-id/12
added       /usr/lib/.build-id/12/356039bc2958ffd85fce73e2924aaf2fb65a47
added       /usr/lib/.build-id/15
added       /usr/lib/.build-id/15/38cd29e2bf43f67e21c3179b0d54e931af58cb
added       /usr/lib/.build-id/16
added       /usr/lib/.build-id/16/48c36d8df346ba6cd74c0d7fc648803a535e6b
added       /usr/lib/.build-id/17
added       /usr/lib/.build-id/17/25bc36403581e6c96278dc2f3f564859fa099b
removed     /usr/lib/.build-id/19
removed     /usr/lib/.build-id/19/ce7b3194edfbcd076af95f481fa05e8bbfa592
added       /usr/lib/.build-id/1d
added       /usr/lib/.build-id/1d/e36dd8fc1e76ead9f0ef8fe697b114b82c0e34
...
```

And would like to be able to filter certain paths out with an option. As a workaround, I pipe the output to grep.

### PR DESCRIPTION
**Pull request by marxin**
Fixes #206

### CODE REVIEW

**Comment by scarabeusiv** [comment]
This is okay, but could you preserve the autor of the previous commit/pr when rebasing?

**Comment by marxin** [comment]
> This is okay, but could you preserve the autor of the previous commit/pr when rebasing?

Done.

**Comment by hroncok** [comment]
Thank you and sorry for not getting into this sooner myself.

**Comment by marxin** [comment]
> Thank you and sorry for not getting into this sooner myself.

You're welcome.

**Pull request merged**
