### PR TITLE
Update users-groups.toml 3proxy

### PR DESCRIPTION
**Pull request by IlyaIndigo**
Added 3proxy group and user for 3proxy tiny proxy servers set.

### CODE REVIEW

**Review by danigm — COMMENTED** [review]
As far as I can tell, this package is not part of Tumbleweed of Leap yet, so I think we shouldn't include.

**Comment by IlyaIndigo** [comment]
> As far as I can tell, this package is not part of Tumbleweed of Leap yet, so I think we shouldn't include.

I actually want to include it in rpmlint first, and then add it to Factory.
I also want to find out if I can use usernames and group names starting with a number?

**Review by danigm — APPROVED** [review]
Okay, looks good with the new `proxy` name.

**Comment by FilippoBonazziSUSE** [comment]
I think this accidentally went to the main branch instead of the opensuse branch... :grimacing: 

@danigm If this is intentional, then can you merge main into opensuse so that we get this change as well?

**Comment by danigm** [comment]
> I think this accidentally went to the main branch instead of the opensuse branch... 😬
> 
> @danigm If this is intentional, then can you merge main into opensuse so that we get this change as well?

Yes, I'll merge main into opensuse today so all the changes to the configs file lands there. We've the `configs/openSUSE` files so I think it's okay to have these changes also in main branch.

**Comment by IlyaIndigo** [comment]
So I should be submitting this PR to the opensuse branch, not main?

Can I send the PR again to the opensuse branch if I need to?

**Comment by IlyaIndigo** [comment]
It might be worth updating the template of this post to make it clearer where to send PRs.
```3proxy.x86_64: W: non-standard-gid /var/lib/3proxy proxy
3proxy.x86_64: W: non-standard-gid /var/lib/3proxy/3proxy.cfg proxy
3proxy.x86_64: W: non-standard-gid /var/log/3proxy proxy
A file in this package is owned by an unregistered group id. To register the
group, please branch the devel:openSUSE:Factory:rpmlint rpmlint package, add
the group to the "config" file and send a submitrequest.
```

**Comment by wfrisch** [comment]
> It might be worth updating the template of this post to make it clearer where to send PRs.

Good idea.
⇒ https://github.com/rpm-software-management/rpmlint/pull/1283

**Pull request merged**
