### PR TITLE
Generate information header prior running the rpmlint wrt issue #38

### PR DESCRIPTION
**Pull request by scarabeusiv**
It prints out version and configs/rpmlintrc everytime.
And in verbose mode it prints out the loaded checks and requested files.

### CODE REVIEW

**Comment by scarabeusiv** [comment]
I wonder if we should use python-wcwidth to detect term lenght and do some wrapping, also if we should use colorama for some nice coloring there...

**Comment by Conan-Kudo** [comment]
> I wonder if we should use python-wcwidth to detect term lenght and do some wrapping, also if we should use colorama for some nice coloring there...

I don't have anything against it, so if you'd like to add it, I don't have a problem with it.

**Comment by scarabeusiv** [comment]
@Conan-Kudo I decided to not add any extra pkg dep and I will just expect nobody will try to use the rpmlint to display chinese/japanese characters.

**Comment by Conan-Kudo** [comment]
@scarabeusiv I don't know if that's a good expectation. The Fedora and openSUSE zh communities do tend to do this, but it's up to you whether it should be fixed now or not...

**Comment by scarabeusiv** [comment]
@Conan-Kudo it will print it out, it will just not be 100% centered as the width of some chars is not 1 character...

**Comment by Conan-Kudo** [comment]
@scarabeusiv Ah, well, then I'm not too concerned right now.

**Pull request merged**
