### PR TITLE
Add SUSE version checks in spec files (#292).

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
The answer is still no.

**Comment by Conan-Kudo** [comment]
@marxin If you want this to be an rpmlint check, it stays downstream.

**Comment by marxin** [comment]
> @marxin If you want this to be an rpmlint check, it stays downstream.

I'm making request to `opensuse` branch which will track the downstream patches on top of master branch.

**Comment by Conan-Kudo** [comment]
@marxin whoops, I didn't notice that... Sorry!

**Pull request closed without merging**
