### PR TITLE
polkit-rules-whitelist: add fudo rules (bsc#1215948)

### PR DESCRIPTION
**Pull request by mgerstner**
Package build log for comparison can be found here:

https://build.opensuse.org/package/live_build_log/security/fudo/openSUSE_Factory/x86_64

### CODE REVIEW

**Comment by FilippoBonazziSUSE** [comment]
Broken, seems to be missing a `[[FileDigestGroup]]` header for the very first `fudo` entry.

**Review by FilippoBonazziSUSE — APPROVED** [review]
You're not specifying the `digester` field for any of the hashes, I assume there is a sane default?

Other than that LGTM.

**Comment by mgerstner** [comment]
> You're not specifying the `digester` field for any of the hashes, I assume there is a sane default?

Yes the default is to hash the unmodified file contents. Since these Polkit rules are Java script we don't have a matching filter yet and the default suffices.

**Comment by FilippoBonazziSUSE** [comment]
I think the mageia-cauldron CI failures are unrelated. Merging

**Pull request merged**
