### PR TITLE
pam-modules: Move pam_timestamp, pam_issue and pam-userdb to different

### PR DESCRIPTION
**Pull request by jsegitz**
rpm-packages

### CODE REVIEW

**Comment by FilippoBonazziSUSE** [comment]
Could you add the bsc# as part of the commit message? It ends up in the package changes

**Review by FilippoBonazziSUSE — APPROVED** [review]
LGTM

**Comment by FilippoBonazziSUSE** [comment]
@marxin @danigm do you know why CI is failing? Is it related to #1051 and it can just be ignored?

**Comment by marxin** [comment]
This is a real warning:
```
./rpmlint/checks/SystemdTmpfilesCheck.py:178:16: C419 Unnecessary list comprehension passed to any() prevents short-circuiting - rewrite as a generator.
./rpmlint/checks/SystemdTmpfilesCheck.py:195:16: C419 Unnecessary list comprehension passed to any() prevents short-circuiting - rewrite as a generator.
```

let me fix it.

**Comment by marxin** [comment]
Please rebase the branch on top of the current `opensuse` branch.

**Review by FilippoBonazziSUSE — APPROVED** [review]

**Comment by marxin** [comment]
Please squash the 2 commits when you Merge this.

**Pull request merged**
