### PR TITLE
Re-add permissions.d whitelisting

### PR DESCRIPTION
**Pull request by acipm**
There is an issue when the "whitelisting" is not in the main permissions profiles, but only in the per-package permission profiles, as they are not considered at all.

This re-adds the first pass of the original check without the original whitelist. Instead we use the FileDIgestLocation "permission" in the opensuse config to ensure files in the permissions.d path to be whitelisted.

Please **don't** merge until @mgerstner reviewed this.

### CODE REVIEW

**Comment by marxin** [comment]
Please rebase it.
@mgerstner : Can you please review it?

**Comment by mgerstner** [comment]
Change looks good to me, but can also here please add test coverage so that this issue will be detected in the future?

**Comment by acipm** [comment]
> Change looks good to me, but can also here please add test coverage so that this issue will be detected in the future?

done

**Comment by mgerstner** [comment]
Looks good to me now. @marxin can merge it if he it also fine with the change.

**Review by marxin — CHANGES_REQUESTED** [review]
Again, can you please submit a test-case to the OBS project?

**Pull request merged**
