### PR TITLE
remove files-attr-not-set check

### PR DESCRIPTION
**Pull request by lnussel**
%defattr(-,root,root) is default since rpm 4.4, released > 10
years go so it's about time to remove that check

### CODE REVIEW

**Comment by lnussel** [comment]
closes #46

**Comment by dirkmueller** [comment]
Ping? this is policy in Fedora even meanwhile I was told (to not set %defattr)

**Comment by scop** [comment]
Just wondering if existence of this check causes an actual problem, i.e. why remove it (besides that most configs end up filtering it and thus need one line in config)? Are there any supported distro versions out there that have only rpm < 4.4? What are the rpm versions corresponding to the last few LSB versions?

**Comment by dirkmueller** [comment]
There is no actual rpm version dependency in the LSB spec as far as I can see, but debian ships rpm 4.8. 

The check wastes valueable cpu cycles and in case the filtering is missing it is spreading outdated advice, which we should prevent imho.

**Comment by scop** [comment]
The oldest rpm versions in supported distros I'm aware of are 4.4.2.3 on RHEL 5.x and friends. If someone knows of a relevant still supported distro that has rpm < 4.4 only, let me know.

**Pull request merged**
