### PR TITLE
Come up with --mini-mode option.

### PR DESCRIPTION
**Pull request by marxin**
The option will be used by rpmlint-lint package wrapper.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
What is this for?

**Comment by marxin** [comment]
In order to keep a limited number of bootstrap cycle packages, we don't want to depend on `pyenchant` and `python39`.
The pull request goes only to `opensuse` branch..

**Comment by marxin** [comment]
Instead of `python39`, we create a `virtualenv`.

**Comment by Conan-Kudo** [comment]
That doesn't solve the problem for you. You'd still need the Python interpreter because virtualenvs do not include the interpreter. Moreover, I don't know why you need an extra wrapper or mode when you could just make those those things weak dependencies instead. The `-mini` convention isn't really for minimized builds, it's for producing hacksaw versions for the OBS build environment. (Personally, I think any package that is called `-mini` in openSUSE needs a better name, because it's clearly wrong.).

It also doesn't actually make sense to have rpmlint as a bootstrap package. It's not _required_ for building packages, and trying to force it in that early is just asking for pain.

**Comment by marxin** [comment]
> That doesn't solve the problem for you. You'd still need the Python interpreter because virtualenvs do not include the interpreter. 

We do have it, but does not work due to: Because it runs rpm, which expands every macro in the spec file, which includes things like %pythons and so on, and so it ends up running python3.9 which then complains bitterly since most of it is removed.

> Moreover, I don't know why you need an extra wrapper or mode when you could just make those those things weak dependencies instead.

Right now, the spellchecker is a weak dependency but generates `(none): W: unable to init enchant, spellchecking disabled.`.

> The `-mini` convention isn't really for minimized builds, it's for producing hacksaw versions for the OBS build environment. 

Yes, we are aware of the hackish approach.

(Personally, I think any package that is called `-mini` in openSUSE needs a better name, because it's clearly wrong.).
> 
> It also doesn't actually make sense to have rpmlint as a bootstrap package. It's not _required_ for building packages, and trying to force it in that early is just asking for pain.

Well, that's decision made by `openSUSE:Factory` people and they want to have rpmlint 2.0 as a mandatory requirement for now.

**Comment by Conan-Kudo** [comment]
> Well, that's decision made by openSUSE:Factory people and they want to have rpmlint 2.0 as a mandatory requirement for now.

As an rpmlint upstream maintainer _and_ an openSUSE person, I would strongly advise _against_ it. When OBS does bootstrap cycles, it goes through and builds them and then rebuilds them again in the main project itself. Because of that, there's no particular reason to make the bootstrap phase include rpmlint. Since hacksaw stuff is already happening there anyway, it's not particularly useful.

**Comment by marxin** [comment]
> As an rpmlint upstream maintainer _and_ an openSUSE person, I would strongly advise _against_ it. When OBS does bootstrap cycles, it goes through and builds them and then rebuilds them again in the main project itself. Because of that, there's no particular reason to make the bootstrap phase include rpmlint. Since hacksaw stuff is already happening there anyway, it's not particularly useful.

I fully got that and support it!
I've just added you to a Jira ticket where the problem was discussed. Feel free to express the need to make `rpmlint` only an optional dependency.

**Comment by Conan-Kudo** [comment]
> > As an rpmlint upstream maintainer _and_ an openSUSE person, I would strongly advise _against_ it. When OBS does bootstrap cycles, it goes through and builds them and then rebuilds them again in the main project itself. Because of that, there's no particular reason to make the bootstrap phase include rpmlint. Since hacksaw stuff is already happening there anyway, it's not particularly useful.
> 
> I fully got that and support it!
> I've just added you to a Jira ticket where the problem was discussed. Feel free to express the need to make `rpmlint` only an optional dependency.

I don't think I can comment in that ticket, as I'm not a SUSE employee. I didn't get a Jira notification about it. 😅

**Comment by marxin** [comment]
> I don't think I can comment in that ticket, as I'm not a SUSE employee. I didn't get a Jira notification about it.

Hm, I found your account and added you to https://jira.suse.com/browse/OBS-88.
Your username seems to be `Pharaoh_Atem`, am I right?

**Comment by Conan-Kudo** [comment]
It is, but I only have access to the `OPENSUSE-` namespace.

**Comment by marxin** [comment]
Ah, that's it :/ So are fine for now with this pull request, that's purely `opensuse`-specific?

**Comment by Conan-Kudo** [comment]
Yeah, sure. I think we need to be careful with how much we add there, because every commit that's openSUSE-specific is tech debt that we _know_ is unsuitable for general use. I originally resisted the creation of the openSUSE vendor branch because I was worried about stuff like this happening, and I wanted it to be more painful to do stuff like this. But here we are...

**Comment by marxin** [comment]
Thanks. Anyway, I would appreciate it if you would discuss the mandatory use of rpmlint in Factory with Dimstar.

**Pull request merged**
