### PR TITLE
Remove one volatile 32-bit test.

### PR DESCRIPTION
**Pull request by marxin**
It's unstable on fedoradev. When I run it locally in podman, it's fine.
But it still fails on the Travis CI.

### CODE REVIEW

**Comment by scarabeusiv** [comment]
@Conan-Kudo any idea why it is flaky on rawhide?

**Comment by Conan-Kudo** [comment]
I'm not sure, @jakubjelinek might know, though?

**Comment by marxin** [comment]
Note the shared library was created with:
```
echo 'void hello() { puts("hello"); }' > hello.c && gcc -o libhello.so -shared hello.c -m32 -Wl,-soname,libhello.so
```

and it's really strange as I cannot reproduce that in `pod2man` run locally on my machine.

**Comment by marxin** [comment]
Well, Fedora Dev has really somehow broken simultaneously installed `x86` and `i686` packages:

```
STEP 3: RUN dnf --nogpgcheck -y install         glibc-devel.i686         gcc         glibc.i686
Last metadata expiration check: 0:01:35 ago on Mon Nov  2 13:19:57 2020.
Dependencies resolved.
================================================================================
 Package              Arch      Version                        Repository  Size
================================================================================
Installing:
 gcc                  x86_64    10.2.1-6.fc34                  rawhide     30 M
 glibc                i686      2.32.9000-12.fc34              rawhide    3.4 M
 glibc-devel          i686      2.32.9000-12.fc34              rawhide    1.1 M
Installing dependencies:
 annobin              x86_64    9.36-1.fc34                    rawhide    131 k
 cpp                  x86_64    10.2.1-6.fc34                  rawhide    9.3 M
 glibc-devel          x86_64    2.32.9000-12.fc34              rawhide    1.1 M
 glibc-headers-x86    noarch    2.32.9000-12.fc34              rawhide    496 k
 isl                  x86_64    0.16.1-12.fc33                 rawhide    876 k
 kernel-headers       x86_64    5.10.0-0.rc1.git0.1.fc34       rawhide    1.2 M
 libgcc               i686      10.2.1-6.fc34                  rawhide    107 k
 libmpc               x86_64    1.1.0-9.fc33                   rawhide     59 k
 libxcrypt            i686      4.4.17-1.fc34                  rawhide    127 k
 libxcrypt-devel      i686      4.4.17-1.fc34                  rawhide     32 k
 libxcrypt-devel      x86_64    4.4.17-1.fc34                  rawhide     32 k
 whois-nls            noarch    5.5.7-1.fc34                   rawhide     34 k
Installing weak dependencies:
 mkpasswd             x86_64    5.5.7-1.fc34                   rawhide     41 k
Transaction Summary
================================================================================
Install  16 Packages
Total download size: 48 M
Installed size: 136 M
Downloading Packages:
(1/16): annobin-9.36-1.fc34.x86_64.rpm          578 kB/s | 131 kB     00:00    
(2/16): glibc-2.32.9000-12.fc34.i686.rpm         18 MB/s | 3.4 MB     00:00    
(3/16): glibc-devel-2.32.9000-12.fc34.i686.rpm   24 MB/s | 1.1 MB     00:00    
(4/16): glibc-devel-2.32.9000-12.fc34.x86_64.rp  26 MB/s | 1.1 MB     00:00    
(5/16): glibc-headers-x86-2.32.9000-12.fc34.noa  12 MB/s | 496 kB     00:00    
(6/16): isl-0.16.1-12.fc33.x86_64.rpm            21 MB/s | 876 kB     00:00    
(7/16): kernel-headers-5.10.0-0.rc1.git0.1.fc34  27 MB/s | 1.2 MB     00:00    
(8/16): gcc-10.2.1-6.fc34.x86_64.rpm             33 MB/s |  30 MB     00:00    
(9/16): libgcc-10.2.1-6.fc34.i686.rpm           403 kB/s | 107 kB     00:00    
(10/16): libmpc-1.1.0-9.fc33.x86_64.rpm         2.0 MB/s |  59 kB     00:00    
(11/16): libxcrypt-4.4.17-1.fc34.i686.rpm       4.2 MB/s | 127 kB     00:00    
(12/16): libxcrypt-devel-4.4.17-1.fc34.i686.rpm 1.1 MB/s |  32 kB     00:00    
(13/16): libxcrypt-devel-4.4.17-1.fc34.x86_64.r 1.1 MB/s |  32 kB     00:00    
(14/16): mkpasswd-5.5.7-1.fc34.x86_64.rpm       1.4 MB/s |  41 kB     00:00    
(15/16): whois-nls-5.5.7-1.fc34.noarch.rpm      1.2 MB/s |  34 kB     00:00    
(16/16): cpp-10.2.1-6.fc34.x86_64.rpm           2.5 MB/s | 9.3 MB     00:03    
--------------------------------------------------------------------------------
Total                                            12 MB/s |  48 MB     00:03     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : kernel-headers-5.10.0-0.rc1.git0.1.fc34.x86_64        1/16 
  Installing       : libgcc-10.2.1-6.fc34.i686                             2/16 
  Running scriptlet: libgcc-10.2.1-6.fc34.i686                             2/16 
  Installing       : whois-nls-5.5.7-1.fc34.noarch                         3/16 
  Running scriptlet: glibc-2.32.9000-12.fc34.i686                          4/16 
  Installing       : glibc-2.32.9000-12.fc34.i686                          4/16 
  Running scriptlet: glibc-2.32.9000-12.fc34.i686                          4/16 
  Installing       : glibc-headers-x86-2.32.9000-12.fc34.noarch            5/16 
  Installing       : libmpc-1.1.0-9.fc33.x86_64                            6/16 
  Installing       : cpp-10.2.1-6.fc34.x86_64                              7/16 
  Installing       : libxcrypt-devel-4.4.17-1.fc34.x86_64                  8/16 
  Installing       : glibc-devel-2.32.9000-12.fc34.x86_64                  9/16 
  Installing       : isl-0.16.1-12.fc33.x86_64                            10/16 
  Installing       : mkpasswd-5.5.7-1.fc34.x86_64                         11/16 
  Installing       : libxcrypt-4.4.17-1.fc34.i686                         12/16 
  Installing       : glibc-devel-2.32.9000-12.fc34.i686                   13/16 
  Installing       : libxcrypt-devel-4.4.17-1.fc34.i686                   14/16 
  Installing       : gcc-10.2.1-6.fc34.x86_64                             15/16 
  Installing       : annobin-9.36-1.fc34.x86_64                           16/16 
  Running scriptlet: annobin-9.36-1.fc34.x86_64                           16/16 
  Verifying        : annobin-9.36-1.fc34.x86_64                            1/16 
  Verifying        : cpp-10.2.1-6.fc34.x86_64                              2/16 
  Verifying        : gcc-10.2.1-6.fc34.x86_64                              3/16 
  Verifying        : glibc-2.32.9000-12.fc34.i686                          4/16 
  Verifying        : glibc-devel-2.32.9000-12.fc34.i686                    5/16 
  Verifying        : glibc-devel-2.32.9000-12.fc34.x86_64                  6/16 
  Verifying        : glibc-headers-x86-2.32.9000-12.fc34.noarch            7/16 
  Verifying        : isl-0.16.1-12.fc33.x86_64                             8/16 
  Verifying        : kernel-headers-5.10.0-0.rc1.git0.1.fc34.x86_64        9/16 
  Verifying        : libgcc-10.2.1-6.fc34.i686                            10/16 
  Verifying        : libmpc-1.1.0-9.fc33.x86_64                           11/16 
  Verifying        : libxcrypt-4.4.17-1.fc34.i686                         12/16 
  Verifying        : libxcrypt-devel-4.4.17-1.fc34.i686                   13/16 
  Verifying        : libxcrypt-devel-4.4.17-1.fc34.x86_64                 14/16 
  Verifying        : mkpasswd-5.5.7-1.fc34.x86_64                         15/16 
  Verifying        : whois-nls-5.5.7-1.fc34.noarch                        16/16 
Installed:
  annobin-9.36-1.fc34.x86_64                                                    
  cpp-10.2.1-6.fc34.x86_64                                                      
  gcc-10.2.1-6.fc34.x86_64                                                      
  glibc-2.32.9000-12.fc34.i686                                                  
  glibc-devel-2.32.9000-12.fc34.i686                                            
  glibc-devel-2.32.9000-12.fc34.x86_64                                          
  glibc-headers-x86-2.32.9000-12.fc34.noarch                                    
  isl-0.16.1-12.fc33.x86_64                                                     
  kernel-headers-5.10.0-0.rc1.git0.1.fc34.x86_64                                
  libgcc-10.2.1-6.fc34.i686                                                     
  libmpc-1.1.0-9.fc33.x86_64                                                    
  libxcrypt-4.4.17-1.fc34.i686                                                  
  libxcrypt-devel-4.4.17-1.fc34.i686                                            
  libxcrypt-devel-4.4.17-1.fc34.x86_64                                          
  mkpasswd-5.5.7-1.fc34.x86_64                                                  
  whois-nls-5.5.7-1.fc34.noarch                                                 
Complete!
226291084e032c70dff0d5cb406710a4ad735a72fb9aff9460aeacb4685ac184
STEP 4: WORKDIR /usr/src/rpmlint
e82e0511b9a692e3b576ff6cb26c50fc98bb8aaa596fe441a596ac160a9d626a
STEP 5: VOLUME /usr/src/rpmlint
STEP 6: COMMIT fedoradev
...
$ podman run -v $(pwd):/usr/src/rpmlint/ $DIST echo 'void hello() { puts("hello"); }' > hello.c && gcc -o libhello.so -shared hello.c -m32 -Wl,-soname,libhello.so && ldd libhello.so
ERRO[0019] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH 
hello.c: In function ‘hello’:
hello.c:1:16: warning: implicit declaration of function ‘puts’ [-Wimplicit-function-declaration]
 void hello() { puts("hello"); }
                ^
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status

```

**Comment by marxin** [comment]
Please merge me the pull request as we've got a failing Travis right now.

**Comment by scarabeusiv** [comment]
I can live with borked travis on fedoradev until they fix it up.

**Pull request closed without merging**
