### PR TITLE
opensuse: explain pull requests more precisely

### PR DESCRIPTION
**Pull request by wfrisch**
i.e. mention our opensuse branch

### CODE REVIEW

**Comment by wfrisch** [comment]
See also the discussion of this PR: https://github.com/rpm-software-management/rpmlint/pull/1267

**Comment by danigm** [comment]
Tests are failing because the merge from main breaks some of them. I've just fixed it so rebasing this PR should fix the tests

**Comment by Conan-Kudo** [comment]
I'm starting to wonder if we should pull the openSUSE branch back out again. I wasn't the biggest fan of it when it was instituted, but it's actively confusing to have openSUSE specific PRs here when we went through a lot of effort to make it easier for distro policies to be maintained externally.

**Comment by FilippoBonazziSUSE** [comment]
I'll defer the discussion about the `opensuse` branch to another occasion when at least @jsegitz and @mgerstner can meaningfully participate (they're both unavailable right now).

For me personally the opensuse branch is not confusing and has been working fine for a long time.

**Review by FilippoBonazziSUSE — APPROVED** [review]
In the meantime, these changes are a net improvement which is both helpful and uncontroversial. Approving.

**Pull request merged**
