### PR TITLE
Use docker volumes instead of copying data

### PR DESCRIPTION
**Pull request by scarabeusiv**
This could allow us to have all the results in travis and as such
ie. upload them to coveralls.

Do not ack this, I will try to get the coveralls uploads first completely working.

### CODE REVIEW

**Comment by junaruga** [comment]
I tried this update for my app's repository.
I faced the volume directory's files are updated as root on the host side directory.
Also podman has different behavior from docker.
See https://github.com/containers/libpod/issues/3432 for detail.

**Comment by scarabeusiv** [comment]
For us we should be fine we care just to grab the .coverage content and publish it, nothing more. Hopefully my last push made it play friendly.

**Comment by scarabeusiv** [comment]
Ok now it works, but we need to grant reading to coveralls.io to actually be able to publish. @Conan-Kudo any ideas whom to poke? It needs to be owner of the group...

**Comment by Conan-Kudo** [comment]
@scarabeusiv That would be @dmach.

**Pull request merged**
