### PR TITLE
Add LogrotateCheck from openSUSE/rpmlint-checks (#227).

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by marxin** [comment]
> Can you please readd the copyright that was in the original file?

That's definitely possible. However, I know that @scarabeusiv asked me to remove the file header with the copyright when I did a port from `rpmlint-check`.
@scarabeusiv: What do you suggest?

**Comment by scarabeusiv** [comment]
That was about those current ones that are listed in authors, if there are new peepz we need to add them there.

**Comment by marxin** [comment]
> That was about those current ones that are listed in authors, if there are new peepz we need to add them there.

Do we have somewhere a list of authors? Or do you mean `git grep '# Author'`?

**Comment by marxin** [comment]
> Do we have somewhere a list of authors? Or do you mean `git grep '# Author'`?

Looking at the history, AUTHORS file was removed in c80f9feac1b83b52e3a7541e4009006cd40c1ead.
So the list of authors will be generated from `git log`.

**Comment by scarabeusiv** [comment]
@marxin ok then I would stick with my other proposal, 2 commits:
1) initial with the orginal author
2) rewrite

**Comment by marxin** [comment]
> @marxin ok then I would stick with my other proposal, 2 commits:
> 
> 1. initial with the orginal author
> 2. rewrite

1

> 1. initial with the orginal author
> 2. rewrite

And will be the author line removal part of **rewrite**?

**Comment by marxin** [comment]
Ok, I made the rebase.

**Pull request merged**
