### PR TITLE
Add cProfile to travis

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@mimi1vx Looks like the Python 3.6 in Leap 15.1 doesn't have the patch to auto-coerce to `C.UTF-8` locale... It's not handling things well..

**Comment by Conan-Kudo** [comment]
@scarabeusiv If it helps, here's the patch from Fedora: https://src.fedoraproject.org/rpms/python36/blob/master/f/00262-pep538_coerce_legacy_c_locale.patch

**Comment by scarabeusiv** [comment]
@mimi1vx please, rebase the new python3 is already published these days.

**Comment by scarabeusiv** [comment]
As this also breaks leap that has pending MU it is just SUSE internal screwup it takes us ages I will merge it too.

**Pull request merged**
