### PR TITLE
configs/Fedora: Sync Fedora rpmlint policies back upstream

### PR DESCRIPTION
**Pull request by Conan-Kudo**

### CODE REVIEW

**Comment by marxin** [comment]
Have you used `tools/generate-fedora-users-groups.py` script for generating the users and groups?
I would recommend splitting lines in `configs/Fedora/users-groups.toml` so that diffs are more readable.

**Comment by Conan-Kudo** [comment]
I had not. I just synced it from [the Fedora Dist-Git repo](https://src.fedoraproject.org/rpms/rpmlint), which @spotrh principally maintains. He might be interested in that tool, though.

**Comment by Conan-Kudo** [comment]
The file is here: https://src.fedoraproject.org/rpms/rpmlint/blob/rawhide/f/users-groups.toml

**Comment by Conan-Kudo** [comment]
But yes, we can split the lines in the config. I just needed this synced to make the rpmlint 2.2.0 release.

**Comment by marxin** [comment]
Sure.

So I would split the lines in the config (and update the header comment) and please think about the usage of the scripts in `tools` folder. Or should we remove it?

**Comment by Conan-Kudo** [comment]
does the script generate these in the correct format (split in newlines)? If so, we can use it going forward, for sure.

**Comment by marxin** [comment]
> does the script generate these in the correct format (split in newlines)?

Dunno, but changing the code would be very easy ;)

**Comment by marxin** [comment]
Note I can't run it as `/usr/share/doc/setup/uidgid` does not exist on openSUSE system.

**Pull request merged**
